# EasyPM v1.5 Config
# Color codes in console logs will not work! Do not even try to use it.

# Messages files are located in /languages/
messages-file: "messages_en-us.yml"

log-prefix: "[EasyPM]"
msg-prefix : "[&aP&bM&r]"

join-alert: true
# /pm settings
# Sound notification settings

enable-notification: true
notification-pitch: 1.0
notification-volume: 1.0
notification-sound: "minecraft:entity.experience_orb.pickup"

database:
  host: localhost # host of your database
  port: 3306 # default port for MySQL
  database: db # name of your database. A database server can contain multiple databases
  user: username
  password: passy