# EasyPM v1.5 Config
# Color codes in console logs will not work! Do not even try to use it.

log-prefix: "[EasyPM]"
msg-prefix : "[&aP&bM&r]"

# /pm settings
# Sound notification settings

enable-notification: true
notification-pitch: 1.0
notification-volume: 1.0
notification-sound: "minecraft:entity.experience_orb.pickup"
