name: EasyPM
version: '${project.version}'
main: com.ustaz1505.easypm.EasyPM
api-version: 1.19
load: STARTUP
authors: [Ustaz1505]
commands:
  pm:
    description: Just Personal message command
    usage: /pm <User> <Message>
    permission: easypm.pm
  easypm:
    description: EasyPM Command
    usage: /easypm <method>
    permission: easypm.easypm
    aliases:
      - epm
