name: EasyPM
version: '1.0.1-SNAPSHOT'
main: com.ustaz1505.easypm.EasyPM
api-version: 1.19
load: STARTUP
authors: [Ustaz1505]
commands:
  pm:
    description: Just Personal message command
    usage: /pm <User> <Message>
    permission: easypm.pm